const CLOUD_NAME = process.env.REACT_APP_CLOUD_NAME;
const CLOUD_KEY_SECRET = process.env.REACT_APP_KEY_SECRET;
const CLOUD_KEY_PRESET = process.env.REACT_APP_PRESET;
const CLOUD_FOLDER_UPLOAD = process.env.REACT_APP_TAG;
export { CLOUD_KEY_PRESET, CLOUD_KEY_SECRET, CLOUD_NAME, CLOUD_FOLDER_UPLOAD };